In [1]:
import pandas as pd

In [2]:
data1 = pd.read_csv('/Users/saisampadaa/Desktop/CAPSTONE PROJECT /Data:Raw:/PCOS_clinical_1.csv')

In [3]:
data1.head

,Sl. No,Patient File No.,PCOS (Y/N),I beta-HCG(mIU/mL),II beta-HCG(mIU/mL),AMH(ng/mL)
0,1,10001,0,1.99,1.99,2.07
1,2,10002,0,60.80,1.99,1.53
2,3,10003,1,494.08,494.08,6.63
3,4,10004,0,1.99,1.99,1.22
4,5,10005,0,801.45,801.45,2.26
...,...,...,...,...,...,...
536,537,10537,0,1.99,1.99,1.7
537,538,10538,0,80.13,1.99,5.6
538,539,10539,0,1.99,1.99,3.7
539,540,10540,0,292.92,1.99,5.2
540,541,10541,1,1.99,1.99,20

In [4]:
data1.corr()

ValueError: could not convert string to float: 'a'

In [5]:
data2 = pd.read_csv('/Users/saisampadaa/Desktop/CAPSTONE PROJECT /Data:Raw:/PCOS_lifestyle.csv')

In [6]:
data2

,Sl. No,Patient File No.,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),...,Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
0,193,193,0,30,69.979147,167.708055,23.185569,12,72,22,...,1,0.0,1,105.483401,76.096379,2,4,10.0,13.0,6.176029
1,360,360,0,36,63.711688,154.055877,25.441392,13,70,18,...,1,0.0,1,115.883740,79.117243,2,3,13.0,11.0,6.824718
2,10,10,0,36,51.848631,149.059804,23.928264,15,80,20,...,0,0.0,0,112.219711,80.919417,1,1,14.0,17.0,2.568691
3,278,278,1,29,66.893988,148.628036,27.894935,15,72,18,...,0,0.0,1,104.619624,69.902681,1,1,12.0,14.0,9.962732
4,71,71,0,33,52.536198,150.767409,23.079564,13,72,18,...,0,0.0,0,99.175454,70.330461,5,2,11.5,4.7,6.655190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,87,87,0,31,66.948922,155.976858,26.662263,15,74,18,...,0,0.0,0,120.323951,83.738573,8,10,15.0,13.0,9.816150
1996,508,508,0,37,64.592788,151.979792,27.681715,11,74,20,...,0,1.0,0,109.738395,76.083303,6,6,19.0,19.0,7.930382
1997,166,166,0,32,47.750129,148.596447,20.041406,11,73,26,...,1,1.0,0,109.570220,61.778231,5,5,14.0,13.0,6.832224
1998,266,266,0,40,31.869660,152.589988,13.793101,15,72,20,...,0,1.0,1,119.456176,79.410616,6,5,18.0,17.0,7.636086
1999,89,89,1,22,70.206568,167.852724,24.791898,13,74,20,...,0,0.0,0,108.275182,76.251829,10,13,15.0,16.0,9.950989

In [7]:
data3 = pd.read_excel('/Users/saisampadaa/Desktop/CAPSTONE PROJECT /Data:Raw:/PCOS_clinical_2.xlsx')

In [8]:
data3

,Instructions to be followed :,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,NaN,NaN,NaN
1,1.0,Kindly ensure that the datas are converted to...,NaN,NaN
2,2.0,Please fill up the entire data set of a patient,NaN,NaN
3,3.0,Manipulated datas if any need to be highlighte...,NaN,NaN
4,4.0,"For every Yes/No questions *** , Indicate Yes...",NaN,NaN
5,5.0,Blood Group indications **,NaN,A+ = 11
6,NaN,NaN,NaN,A- = 12
7,NaN,NaN,NaN,B+ = 13
8,NaN,NaN,NaN,B- = 14
9,NaN,NaN,NaN,O+ =15
10,NaN,NaN,NaN,O- = 16
11,NaN,NaN,NaN,AB+ =17
12,NaN,NaN,NaN,AB- = 18
13,6.0,Blood pressure should be entered as systolic a...,NaN,NaN
14,7.0,Additional informations if any should be kept ...,NaN,NaN
15,8.0,Please ensure that no NaN ( Non Numeric values...,NaN,NaN
16,9.0,RBS means Random glucose test,NaN,NaN
17,10.0,Beta-HCG cases are mentioned as Case I and II ...,NaN,NaN
18,11.0,In case sparing a blank space kindly fill the ...,NaN,NaN
19,12.0,If the patient is PCOS Fill the cell with gree...,NaN,NaN

In [9]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sl. No                  2000 non-null   int64
 1   Patient File No.        2000 non-null   int64
 2   PCOS (Y/N)              2000 non-null   int64
 3    Age (yrs)              2000 non-null   int64
 4   Weight (Kg)             2000 non-null   float64
 5   Height(Cm)              2000 non-null   float64
 6   BMI                     2000 non-null   float64
 7   Blood Group             2000 non-null   int64
 8   Pulse rate(bpm)         2000 non-null   int64
 9   RR (breaths/min)        2000 non-null   int64
 10  Hb(g/dl)                2000 non-null   float64
 11  Cycle(R/I)              2000 non-null   int64
 12  Cycle length(days)      2000 non-null   int64
 13  Marraige Status (Yrs)   1997 non-null   float64
 14  Pregnant(Y/N)           2000 non-null   int64
 15  No. of abortions        2000 non-null   int64
 16    I   beta-HCG(mIU/mL)  2000 non-null   float64
 17  II    beta-HCG(mIU/mL)  2000 non-null   object
 18  FSH(mIU/mL)             2000 non-null   float64
 19  LH(mIU/mL)              2000 non-null   float64
 20  FSH/LH                  2000 non-null   float64
 21  Hip(inch)               2000 non-null   int64
 22  Waist(inch)             2000 non-null   int64
 23  Waist:Hip Ratio         2000 non-null   float64
 24  TSH (mIU/L)             2000 non-null   float64
 25  AMH(ng/mL)              2000 non-null   object
 26  PRL(ng/mL)              2000 non-null   float64
 27  Vit D3 (ng/mL)          2000 non-null   float64
 28  PRG(ng/mL)              2000 non-null   float64
 29  RBS(mg/dl)              2000 non-null   float64
 30  Weight gain(Y/N)        2000 non-null   int64
 31  hair growth(Y/N)        2000 non-null   int64
 32  Skin darkening (Y/N)    2000 non-null   int64
 33  Hair loss(Y/N)          2000 non-null   int64
 34  Pimples(Y/N)            2000 non-null   int64
 35  Fast food (Y/N)         2000 non-null   float64
 36  Reg.Exercise(Y/N)       2000 non-null   int64
 37  BP _Systolic (mmHg)     2000 non-null   float64
 38  BP _Diastolic (mmHg)    2000 non-null   float64
 39  Follicle No. (L)        2000 non-null   int64
 40  Follicle No. (R)        2000 non-null   int64
 41  Avg. F size (L) (mm)    2000 non-null   float64
 42  Avg. F size (R) (mm)    2000 non-null   float64
 43  Endometrium (mm)        2000 non-null   float64
dtypes: float64(21), int64(21), object(2)
memory usage: 687.6+ KB

In [10]:
data2.head()

,Sl. No,Patient File No.,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),...,Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
0,193,193,0,30,69.979147,167.708055,23.185569,12,72,22,...,1,0.0,1,105.483401,76.096379,2,4,10.0,13.0,6.176029
1,360,360,0,36,63.711688,154.055877,25.441392,13,70,18,...,1,0.0,1,115.883740,79.117243,2,3,13.0,11.0,6.824718
2,10,10,0,36,51.848631,149.059804,23.928264,15,80,20,...,0,0.0,0,112.219711,80.919417,1,1,14.0,17.0,2.568691
3,278,278,1,29,66.893988,148.628036,27.894935,15,72,18,...,0,0.0,1,104.619624,69.902681,1,1,12.0,14.0,9.962732
4,71,71,0,33,52.536198,150.767409,23.079564,13,72,18,...,0,0.0,0,99.175454,70.330461,5,2,11.5,4.7,6.655190

In [11]:
data2['PCOS (Y/N)'].value_counts()

PCOS (Y/N)
0    1392
1     608
Name: count, dtype: int64

In [12]:
data = data2.copy()

In [13]:
data.drop(
    columns=['Sl. No', 'Patient File No.'],
    inplace=True
)

In [14]:
data.shape

(2000, 42)

In [15]:
missing = data.isnull().sum()
missing[missing > 0]

Marraige Status (Yrs)    3
dtype: int64

In [16]:
data['Marraige Status (Yrs)'] = data['Marraige Status (Yrs)'].fillna(
    data['Marraige Status (Yrs)'].median()
)

In [17]:
data.select_dtypes(include='object').columns

Index(['II    beta-HCG(mIU/mL)', 'AMH(ng/mL)'], dtype='object')

In [18]:
data['AMH(ng/mL)'] = pd.to_numeric(
    data['AMH(ng/mL)'],
    errors='coerce'
)

data['II    beta-HCG(mIU/mL)'] = pd.to_numeric(
    data['II    beta-HCG(mIU/mL)'],
    errors='coerce'
)

In [19]:
data.isnull().sum().sort_values(ascending=False)

II    beta-HCG(mIU/mL)    5
AMH(ng/mL)                3
Hair loss(Y/N)            0
PRL(ng/mL)                0
Vit D3 (ng/mL)            0
PRG(ng/mL)                0
RBS(mg/dl)                0
Weight gain(Y/N)          0
hair growth(Y/N)          0
Skin darkening (Y/N)      0
PCOS (Y/N)                0
TSH (mIU/L)               0
Fast food (Y/N)           0
Reg.Exercise(Y/N)         0
BP _Systolic (mmHg)       0
BP _Diastolic (mmHg)      0
Follicle No. (L)          0
Follicle No. (R)          0
Avg. F size (L) (mm)      0
Avg. F size (R) (mm)      0
Pimples(Y/N)              0
Waist:Hip Ratio           0
 Age (yrs)                0
Waist(inch)               0
Weight (Kg)               0
Height(Cm)                0
BMI                       0
Blood Group               0
Pulse rate(bpm)           0
RR (breaths/min)          0
Hb(g/dl)                  0
Cycle(R/I)                0
Cycle length(days)        0
Marraige Status (Yrs)     0
Pregnant(Y/N)             0
No. of abortions          0
  I   beta-HCG(mIU/mL)    0
FSH(mIU/mL)               0
LH(mIU/mL)                0
FSH/LH                    0
Hip(inch)                 0
Endometrium (mm)          0
dtype: int64

In [20]:
for col in data.columns:
    if data[col].dtype in ['int64', 'float64']:
        data[col] = data[col].fillna(data[col].median())

In [21]:
data.duplicated().sum()

0

In [22]:
data['PCOS (Y/N)'].value_counts()

PCOS (Y/N)
0    1392
1     608
Name: count, dtype: int64

In [23]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
PCOS (Y/N),2000.0,0.304000,0.460098,0.000000,0.000000,0.000000,1.000000,1.000000
Age (yrs),2000.0,31.354000,5.449820,20.000000,28.000000,31.000000,35.000000,48.000000
Weight (Kg),2000.0,59.527068,11.445212,30.739215,52.248684,58.538632,65.519518,113.379053
Height(Cm),2000.0,156.416496,6.044243,136.539081,152.169130,156.433674,160.064790,180.388539
BMI,2000.0,24.284184,4.132187,11.939138,21.765743,24.188981,26.600461,40.449415
Blood Group,2000.0,13.788000,1.832958,11.000000,13.000000,14.000000,15.000000,18.000000
Pulse rate(bpm),2000.0,73.241000,4.098941,13.000000,72.000000,72.000000,74.000000,82.000000
RR (breaths/min),2000.0,19.232000,1.740601,16.000000,18.000000,18.000000,20.000000,28.000000
Hb(g/dl),2000.0,11.153785,0.868073,8.500000,10.500000,11.000000,11.700000,14.800000
Cycle(R/I),2000.0,2.535500,0.888332,2.000000,2.000000,2.000000,4.000000,5.000000
Cycle length(days),2000.0,4.972500,1.422588,0.000000,5.000000,5.000000,5.000000,12.000000
Marraige Status (Yrs),2000.0,7.577850,4.816086,0.000000,4.000000,7.000000,10.000000,30.000000
Pregnant(Y/N),2000.0,0.381500,0.485876,0.000000,0.000000,0.000000,1.000000,1.000000
No. of abortions,2000.0,0.301000,0.716698,0.000000,0.000000,0.000000,0.000000,5.000000
I beta-HCG(mIU/mL),2000.0,640.599939,3300.935367,1.300000,1.990000,12.370000,300.530000,32460.970000
II beta-HCG(mIU/mL),2000.0,220.922315,1370.954155,0.990000,1.990000,1.990000,98.145000,25000.000000
FSH(mIU/mL),2000.0,12.935498,195.419736,0.210000,3.390000,4.860000,6.470000,5052.000000
LH(mIU/mL),2000.0,9.873493,119.064554,0.020000,1.020000,2.330000,3.830000,2018.000000
FSH/LH,2000.0,6.799150,56.122050,0.000000,1.420000,2.130000,3.870000,1372.830000
Hip(inch),2000.0,37.995500,3.988914,26.000000,36.000000,38.000000,40.000000,48.000000
Waist(inch),2000.0,33.769000,3.590416,24.000000,32.000000,34.000000,36.000000,47.000000
Waist:Hip Ratio,2000.0,0.889800,0.046565,0.760000,0.850000,0.890000,0.930000,0.980000
TSH (mIU/L),2000.0,3.000138,3.237188,0.040000,1.510000,2.285000,3.642500,65.000000
AMH(ng/mL),2000.0,5.964183,6.608978,0.100000,2.140000,3.900000,7.700000,66.000000
PRL(ng/mL),2000.0,24.486545,15.787810,0.400000,14.645000,21.780000,29.720000,128.240000
Vit D3 (ng/mL),2000.0,40.377968,254.819006,0.000000,20.800000,26.100000,35.660000,6014.660000
PRG(ng/mL),2000.0,0.688444,4.109938,0.047000,0.250000,0.320000,0.460000,85.000000
RBS(mg/dl),2000.0,99.809800,19.488640,60.000000,92.000000,100.000000,107.000000,350.000000
Weight gain(Y/N),2000.0,0.380500,0.485631,0.000000,0.000000,0.000000,1.000000,1.000000
hair growth(Y/N),2000.0,0.274500,0.446374,0.000000,0.000000,0.000000,1.000000,1.000000
Skin darkening (Y/N),2000.0,0.290000,0.453876,0.000000,0.000000,0.000000,1.000000,1.000000
Hair loss(Y/N),2000.0,0.443500,0.496922,0.000000,0.000000,0.000000,1.000000,1.000000
Pimples(Y/N),2000.0,0.477000,0.499596,0.000000,0.000000,0.000000,1.000000,1.000000
Fast food (Y/N),2000.0,0.517000,0.499836,0.000000,0.000000,1.000000,1.000000,1.000000
Reg.Exercise(Y/N),2000.0,0.257500,0.437366,0.000000,0.000000,0.000000,1.000000,1.000000
BP _Systolic (mmHg),2000.0,114.701590,7.564600,11.525778,109.564746,114.558163,120.190386,144.980616
BP _Diastolic (mmHg),2000.0,76.989127,6.085313,7.680842,72.433707,78.340745,81.186301,104.267012
Follicle No. (L),2000.0,6.090000,4.230940,0.000000,3.000000,5.000000,8.250000,22.000000
Follicle No. (R),2000.0,6.503500,4.373620,0.000000,3.000000,6.000000,9.000000,20.000000
Avg. F size (L) (mm),2000.0,14.879300,3.641161,0.000000,13.000000,15.000000,18.000000,24.000000
Avg. F size (R) (mm),2000.0,15.410320,3.270965,0.000000,13.000000,16.000000,18.000000,24.000000
Endometrium (mm),2000.0,8.571637,2.217999,0.000000,7.099641,8.434753,9.876932,18.675452

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 42 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   PCOS (Y/N)              2000 non-null   int64
 1    Age (yrs)              2000 non-null   int64
 2   Weight (Kg)             2000 non-null   float64
 3   Height(Cm)              2000 non-null   float64
 4   BMI                     2000 non-null   float64
 5   Blood Group             2000 non-null   int64
 6   Pulse rate(bpm)         2000 non-null   int64
 7   RR (breaths/min)        2000 non-null   int64
 8   Hb(g/dl)                2000 non-null   float64
 9   Cycle(R/I)              2000 non-null   int64
 10  Cycle length(days)      2000 non-null   int64
 11  Marraige Status (Yrs)   2000 non-null   float64
 12  Pregnant(Y/N)           2000 non-null   int64
 13  No. of abortions        2000 non-null   int64
 14    I   beta-HCG(mIU/mL)  2000 non-null   float64
 15  II    beta-HCG(mIU/mL)  2000 non-null   float64
 16  FSH(mIU/mL)             2000 non-null   float64
 17  LH(mIU/mL)              2000 non-null   float64
 18  FSH/LH                  2000 non-null   float64
 19  Hip(inch)               2000 non-null   int64
 20  Waist(inch)             2000 non-null   int64
 21  Waist:Hip Ratio         2000 non-null   float64
 22  TSH (mIU/L)             2000 non-null   float64
 23  AMH(ng/mL)              2000 non-null   float64
 24  PRL(ng/mL)              2000 non-null   float64
 25  Vit D3 (ng/mL)          2000 non-null   float64
 26  PRG(ng/mL)              2000 non-null   float64
 27  RBS(mg/dl)              2000 non-null   float64
 28  Weight gain(Y/N)        2000 non-null   int64
 29  hair growth(Y/N)        2000 non-null   int64
 30  Skin darkening (Y/N)    2000 non-null   int64
 31  Hair loss(Y/N)          2000 non-null   int64
 32  Pimples(Y/N)            2000 non-null   int64
 33  Fast food (Y/N)         2000 non-null   float64
 34  Reg.Exercise(Y/N)       2000 non-null   int64
 35  BP _Systolic (mmHg)     2000 non-null   float64
 36  BP _Diastolic (mmHg)    2000 non-null   float64
 37  Follicle No. (L)        2000 non-null   int64
 38  Follicle No. (R)        2000 non-null   int64
 39  Avg. F size (L) (mm)    2000 non-null   float64
 40  Avg. F size (R) (mm)    2000 non-null   float64
 41  Endometrium (mm)        2000 non-null   float64
dtypes: float64(23), int64(19)
memory usage: 656.4 KB

In [25]:
data.to_csv(
    "pcos_cleaned.csv",
    index=False
)

In [26]:
data.select_dtypes(include='object').columns

Index([], dtype='object')

In [27]:
data.isnull().sum().sort_values(ascending=False).head(20)

PCOS (Y/N)              0
Hair loss(Y/N)          0
AMH(ng/mL)              0
PRL(ng/mL)              0
Vit D3 (ng/mL)          0
PRG(ng/mL)              0
RBS(mg/dl)              0
Weight gain(Y/N)        0
hair growth(Y/N)        0
Skin darkening (Y/N)    0
Pimples(Y/N)            0
 Age (yrs)              0
Fast food (Y/N)         0
Reg.Exercise(Y/N)       0
BP _Systolic (mmHg)     0
BP _Diastolic (mmHg)    0
Follicle No. (L)        0
Follicle No. (R)        0
Avg. F size (L) (mm)    0
Avg. F size (R) (mm)    0
dtype: int64

In [28]:
data.duplicated().sum()

0

In [29]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
PCOS (Y/N),2000.0,0.304000,0.460098,0.000000,0.000000,0.000000,1.000000,1.000000
Age (yrs),2000.0,31.354000,5.449820,20.000000,28.000000,31.000000,35.000000,48.000000
Weight (Kg),2000.0,59.527068,11.445212,30.739215,52.248684,58.538632,65.519518,113.379053
Height(Cm),2000.0,156.416496,6.044243,136.539081,152.169130,156.433674,160.064790,180.388539
BMI,2000.0,24.284184,4.132187,11.939138,21.765743,24.188981,26.600461,40.449415
Blood Group,2000.0,13.788000,1.832958,11.000000,13.000000,14.000000,15.000000,18.000000
Pulse rate(bpm),2000.0,73.241000,4.098941,13.000000,72.000000,72.000000,74.000000,82.000000
RR (breaths/min),2000.0,19.232000,1.740601,16.000000,18.000000,18.000000,20.000000,28.000000
Hb(g/dl),2000.0,11.153785,0.868073,8.500000,10.500000,11.000000,11.700000,14.800000
Cycle(R/I),2000.0,2.535500,0.888332,2.000000,2.000000,2.000000,4.000000,5.000000
Cycle length(days),2000.0,4.972500,1.422588,0.000000,5.000000,5.000000,5.000000,12.000000
Marraige Status (Yrs),2000.0,7.577850,4.816086,0.000000,4.000000,7.000000,10.000000,30.000000
Pregnant(Y/N),2000.0,0.381500,0.485876,0.000000,0.000000,0.000000,1.000000,1.000000
No. of abortions,2000.0,0.301000,0.716698,0.000000,0.000000,0.000000,0.000000,5.000000
I beta-HCG(mIU/mL),2000.0,640.599939,3300.935367,1.300000,1.990000,12.370000,300.530000,32460.970000
II beta-HCG(mIU/mL),2000.0,220.922315,1370.954155,0.990000,1.990000,1.990000,98.145000,25000.000000
FSH(mIU/mL),2000.0,12.935498,195.419736,0.210000,3.390000,4.860000,6.470000,5052.000000
LH(mIU/mL),2000.0,9.873493,119.064554,0.020000,1.020000,2.330000,3.830000,2018.000000
FSH/LH,2000.0,6.799150,56.122050,0.000000,1.420000,2.130000,3.870000,1372.830000
Hip(inch),2000.0,37.995500,3.988914,26.000000,36.000000,38.000000,40.000000,48.000000
Waist(inch),2000.0,33.769000,3.590416,24.000000,32.000000,34.000000,36.000000,47.000000
Waist:Hip Ratio,2000.0,0.889800,0.046565,0.760000,0.850000,0.890000,0.930000,0.980000
TSH (mIU/L),2000.0,3.000138,3.237188,0.040000,1.510000,2.285000,3.642500,65.000000
AMH(ng/mL),2000.0,5.964183,6.608978,0.100000,2.140000,3.900000,7.700000,66.000000
PRL(ng/mL),2000.0,24.486545,15.787810,0.400000,14.645000,21.780000,29.720000,128.240000
Vit D3 (ng/mL),2000.0,40.377968,254.819006,0.000000,20.800000,26.100000,35.660000,6014.660000
PRG(ng/mL),2000.0,0.688444,4.109938,0.047000,0.250000,0.320000,0.460000,85.000000
RBS(mg/dl),2000.0,99.809800,19.488640,60.000000,92.000000,100.000000,107.000000,350.000000
Weight gain(Y/N),2000.0,0.380500,0.485631,0.000000,0.000000,0.000000,1.000000,1.000000
hair growth(Y/N),2000.0,0.274500,0.446374,0.000000,0.000000,0.000000,1.000000,1.000000
Skin darkening (Y/N),2000.0,0.290000,0.453876,0.000000,0.000000,0.000000,1.000000,1.000000
Hair loss(Y/N),2000.0,0.443500,0.496922,0.000000,0.000000,0.000000,1.000000,1.000000
Pimples(Y/N),2000.0,0.477000,0.499596,0.000000,0.000000,0.000000,1.000000,1.000000
Fast food (Y/N),2000.0,0.517000,0.499836,0.000000,0.000000,1.000000,1.000000,1.000000
Reg.Exercise(Y/N),2000.0,0.257500,0.437366,0.000000,0.000000,0.000000,1.000000,1.000000
BP _Systolic (mmHg),2000.0,114.701590,7.564600,11.525778,109.564746,114.558163,120.190386,144.980616
BP _Diastolic (mmHg),2000.0,76.989127,6.085313,7.680842,72.433707,78.340745,81.186301,104.267012
Follicle No. (L),2000.0,6.090000,4.230940,0.000000,3.000000,5.000000,8.250000,22.000000
Follicle No. (R),2000.0,6.503500,4.373620,0.000000,3.000000,6.000000,9.000000,20.000000
Avg. F size (L) (mm),2000.0,14.879300,3.641161,0.000000,13.000000,15.000000,18.000000,24.000000
Avg. F size (R) (mm),2000.0,15.410320,3.270965,0.000000,13.000000,16.000000,18.000000,24.000000
Endometrium (mm),2000.0,8.571637,2.217999,0.000000,7.099641,8.434753,9.876932,18.675452

In [30]:
data[data['Pulse rate(bpm)'] < 40]

KeyError: 'Pulse rate(bpm)'

In [31]:
print(data.columns.tolist())

['PCOS (Y/N)', ' Age (yrs)', 'Weight (Kg)', 'Height(Cm) ', 'BMI', 'Blood Group', 'Pulse rate(bpm) ', 'RR (breaths/min)', 'Hb(g/dl)', 'Cycle(R/I)', 'Cycle length(days)', 'Marraige Status (Yrs)', 'Pregnant(Y/N)', 'No. of abortions', '  I   beta-HCG(mIU/mL)', 'II    beta-HCG(mIU/mL)', 'FSH(mIU/mL)', 'LH(mIU/mL)', 'FSH/LH', 'Hip(inch)', 'Waist(inch)', 'Waist:Hip Ratio', 'TSH (mIU/L)', 'AMH(ng/mL)', 'PRL(ng/mL)', 'Vit D3 (ng/mL)', 'PRG(ng/mL)', 'RBS(mg/dl)', 'Weight gain(Y/N)', 'hair growth(Y/N)', 'Skin darkening (Y/N)', 'Hair loss(Y/N)', 'Pimples(Y/N)', 'Fast food (Y/N)', 'Reg.Exercise(Y/N)', 'BP _Systolic (mmHg)', 'BP _Diastolic (mmHg)', 'Follicle No. (L)', 'Follicle No. (R)', 'Avg. F size (L) (mm)', 'Avg. F size (R) (mm)', 'Endometrium (mm)']

In [32]:
for i, col in enumerate(data.columns):
    print(i, col)

0 PCOS (Y/N)
1  Age (yrs)
2 Weight (Kg)
3 Height(Cm)
4 BMI
5 Blood Group
6 Pulse rate(bpm)
7 RR (breaths/min)
8 Hb(g/dl)
9 Cycle(R/I)
10 Cycle length(days)
11 Marraige Status (Yrs)
12 Pregnant(Y/N)
13 No. of abortions
14   I   beta-HCG(mIU/mL)
15 II    beta-HCG(mIU/mL)
16 FSH(mIU/mL)
17 LH(mIU/mL)
18 FSH/LH
19 Hip(inch)
20 Waist(inch)
21 Waist:Hip Ratio
22 TSH (mIU/L)
23 AMH(ng/mL)
24 PRL(ng/mL)
25 Vit D3 (ng/mL)
26 PRG(ng/mL)
27 RBS(mg/dl)
28 Weight gain(Y/N)
29 hair growth(Y/N)
30 Skin darkening (Y/N)
31 Hair loss(Y/N)
32 Pimples(Y/N)
33 Fast food (Y/N)
34 Reg.Exercise(Y/N)
35 BP _Systolic (mmHg)
36 BP _Diastolic (mmHg)
37 Follicle No. (L)
38 Follicle No. (R)
39 Avg. F size (L) (mm)
40 Avg. F size (R) (mm)
41 Endometrium (mm)

In [33]:
data.columns.tolist()

['PCOS (Y/N)',
 ' Age (yrs)',
 'Weight (Kg)',
 'Height(Cm) ',
 'BMI',
 'Blood Group',
 'Pulse rate(bpm) ',
 'RR (breaths/min)',
 'Hb(g/dl)',
 'Cycle(R/I)',
 'Cycle length(days)',
 'Marraige Status (Yrs)',
 'Pregnant(Y/N)',
 'No. of abortions',
 '  I   beta-HCG(mIU/mL)',
 'II    beta-HCG(mIU/mL)',
 'FSH(mIU/mL)',
 'LH(mIU/mL)',
 'FSH/LH',
 'Hip(inch)',
 'Waist(inch)',
 'Waist:Hip Ratio',
 'TSH (mIU/L)',
 'AMH(ng/mL)',
 'PRL(ng/mL)',
 'Vit D3 (ng/mL)',
 'PRG(ng/mL)',
 'RBS(mg/dl)',
 'Weight gain(Y/N)',
 'hair growth(Y/N)',
 'Skin darkening (Y/N)',
 'Hair loss(Y/N)',
 'Pimples(Y/N)',
 'Fast food (Y/N)',
 'Reg.Exercise(Y/N)',
 'BP _Systolic (mmHg)',
 'BP _Diastolic (mmHg)',
 'Follicle No. (L)',
 'Follicle No. (R)',
 'Avg. F size (L) (mm)',
 'Avg. F size (R) (mm)',
 'Endometrium (mm)']

In [34]:
data[data['Pulse rate(bpm) '] < 40]

,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),Hb(g/dl),Cycle(R/I),...,Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
100,0,31,47.504533,155.217072,20.062901,15,13,18,11.0,2,...,1,0.0,0,114.708759,72.052982,8,5,17.0,15.0,8.915929
335,0,30,60.114401,168.553304,20.948460,11,18,20,12.0,2,...,0,1.0,1,120.829692,70.665205,4,3,14.0,18.0,8.116710
629,0,31,51.653131,153.674464,19.926153,15,13,18,11.0,2,...,1,0.0,0,114.167088,69.735318,8,5,17.0,15.0,8.298456
1252,0,30,59.873900,170.303031,21.911739,11,18,20,12.0,2,...,0,1.0,1,121.713928,73.432126,4,3,14.0,18.0,8.047062
1298,0,30,60.894628,168.339166,21.944444,11,18,20,12.0,2,...,0,1.0,1,115.726288,68.530995,4,3,14.0,18.0,8.366555
1591,0,30,59.919243,170.424655,22.476135,11,18,20,12.0,2,...,0,1.0,1,114.698209,66.786352,4,3,14.0,18.0,8.798048

In [35]:
median_pulse = data['Pulse rate(bpm) '].median()

data.loc[data['Pulse rate(bpm) '] < 40, 'Pulse rate(bpm) '] = median_pulse

In [36]:
data[data['Pulse rate(bpm) '] < 40]

Empty DataFrame
Columns: [PCOS (Y/N),  Age (yrs), Weight (Kg), Height(Cm) , BMI, Blood Group, Pulse rate(bpm) , RR (breaths/min), Hb(g/dl), Cycle(R/I), Cycle length(days), Marraige Status (Yrs), Pregnant(Y/N), No. of abortions,   I   beta-HCG(mIU/mL), II    beta-HCG(mIU/mL), FSH(mIU/mL), LH(mIU/mL), FSH/LH, Hip(inch), Waist(inch), Waist:Hip Ratio, TSH (mIU/L), AMH(ng/mL), PRL(ng/mL), Vit D3 (ng/mL), PRG(ng/mL), RBS(mg/dl), Weight gain(Y/N), hair growth(Y/N), Skin darkening (Y/N), Hair loss(Y/N), Pimples(Y/N), Fast food (Y/N), Reg.Exercise(Y/N), BP _Systolic (mmHg), BP _Diastolic (mmHg), Follicle No. (L), Follicle No. (R), Avg. F size (L) (mm), Avg. F size (R) (mm), Endometrium (mm)]
Index: []

[0 rows x 42 columns]

In [37]:
data['Pulse rate(bpm) '].describe()

count    2000.000000
mean       73.408000
std         2.653499
min        70.000000
25%        72.000000
50%        72.000000
75%        74.000000
max        82.000000
Name: Pulse rate(bpm) , dtype: float64

In [38]:
data.describe().T[['min', 'max']]

                               min           max
PCOS (Y/N)                0.000000      1.000000
 Age (yrs)               20.000000     48.000000
Weight (Kg)              30.739215    113.379053
Height(Cm)              136.539081    180.388539
BMI                      11.939138     40.449415
Blood Group              11.000000     18.000000
Pulse rate(bpm)          70.000000     82.000000
RR (breaths/min)         16.000000     28.000000
Hb(g/dl)                  8.500000     14.800000
Cycle(R/I)                2.000000      5.000000
Cycle length(days)        0.000000     12.000000
Marraige Status (Yrs)     0.000000     30.000000
Pregnant(Y/N)             0.000000      1.000000
No. of abortions          0.000000      5.000000
  I   beta-HCG(mIU/mL)    1.300000  32460.970000
II    beta-HCG(mIU/mL)    0.990000  25000.000000
FSH(mIU/mL)               0.210000   5052.000000
LH(mIU/mL)                0.020000   2018.000000
FSH/LH                    0.000000   1372.830000
Hip(inch)                26.000000     48.000000
Waist(inch)              24.000000     47.000000
Waist:Hip Ratio           0.760000      0.980000
TSH (mIU/L)               0.040000     65.000000
AMH(ng/mL)                0.100000     66.000000
PRL(ng/mL)                0.400000    128.240000
Vit D3 (ng/mL)            0.000000   6014.660000
PRG(ng/mL)                0.047000     85.000000
RBS(mg/dl)               60.000000    350.000000
Weight gain(Y/N)          0.000000      1.000000
hair growth(Y/N)          0.000000      1.000000
Skin darkening (Y/N)      0.000000      1.000000
Hair loss(Y/N)            0.000000      1.000000
Pimples(Y/N)              0.000000      1.000000
Fast food (Y/N)           0.000000      1.000000
Reg.Exercise(Y/N)         0.000000      1.000000
BP _Systolic (mmHg)      11.525778    144.980616
BP _Diastolic (mmHg)      7.680842    104.267012
Follicle No. (L)          0.000000     22.000000
Follicle No. (R)          0.000000     20.000000
Avg. F size (L) (mm)      0.000000     24.000000
Avg. F size (R) (mm)      0.000000     24.000000
Endometrium (mm)          0.000000     18.675452

In [39]:
data[data['FSH(mIU/mL)'] > 100]

,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),Hb(g/dl),Cycle(R/I),...,Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
212,0,29,53.851782,161.942982,20.178061,15,72,18,10.2,2,...,1,1.0,0,109.662800,80.936730,6,4,16.0,17.0,5.400293
416,0,29,52.955206,159.581299,20.929324,15,72,18,10.2,2,...,1,1.0,0,107.397820,79.063894,6,4,16.0,17.0,6.496181
1073,0,29,53.855147,162.093832,20.736495,15,72,18,10.2,2,...,1,1.0,0,115.002884,77.758556,6,4,16.0,17.0,6.368825

In [40]:
median_fsh = data['FSH(mIU/mL)'].median()

data.loc[
    data['FSH(mIU/mL)'] > 100,
    'FSH(mIU/mL)'
] = median_fsh

In [41]:
data[data['LH(mIU/mL)'] > 100]

,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),Hb(g/dl),Cycle(R/I),...,Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
227,1,32,49.850587,151.055644,22.758939,13,70,18,9.4,2,...,1,0.0,1,111.556479,82.664167,6,7,18.0,18.0,8.400256
271,1,32,52.243454,150.611032,22.352134,13,70,18,9.4,2,...,1,0.0,1,110.669487,83.995610,6,7,18.0,18.0,9.524824
833,1,32,50.408667,148.975699,22.456210,13,70,18,9.4,2,...,1,0.0,1,113.221260,82.269594,6,7,18.0,18.0,8.293550
941,1,32,51.339229,150.172063,23.558912,13,70,18,9.4,2,...,1,0.0,1,109.888014,77.847365,6,7,18.0,18.0,8.290236
999,1,32,54.144126,150.114467,22.521351,13,70,18,9.4,2,...,1,0.0,1,107.075579,79.613187,6,7,18.0,18.0,8.505423
1615,1,32,50.928996,150.637503,23.979689,13,70,18,9.4,2,...,1,0.0,1,114.644222,82.606323,6,7,18.0,18.0,8.258350
1664,1,32,49.450043,149.260978,23.574741,13,70,18,9.4,2,...,1,0.0,1,113.134225,79.895050,6,7,18.0,18.0,8.787299

In [42]:
data[data['FSH/LH'] > 20]

,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),Hb(g/dl),Cycle(R/I),...,Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
9,0,40,57.576129,156.596777,23.227606,11,80,20,10.3,2,...,0,0.0,0,121.756683,72.242461,11,9,17.0,18.0,4.693380
25,0,36,54.299809,153.621101,24.137275,13,74,18,10.0,2,...,0,1.0,0,105.204021,76.472985,4,1,22.0,14.0,11.193793
51,1,30,70.681336,150.429917,30.173734,16,74,18,11.7,4,...,0,1.0,0,123.236775,79.199786,8,6,12.0,11.0,4.498775
106,1,30,71.928179,150.675084,31.719376,16,74,18,11.7,4,...,0,1.0,0,115.773042,77.448332,8,6,12.0,11.0,4.815907
144,0,27,58.239245,159.741685,23.940084,15,70,18,10.8,2,...,1,0.0,0,110.111916,71.399460,8,5,18.0,15.0,8.406593
167,0,36,56.337053,155.383765,22.206473,13,74,18,10.0,2,...,0,1.0,0,107.689090,77.050943,4,1,22.0,14.0,11.167346
212,0,29,53.851782,161.942982,20.178061,15,72,18,10.2,2,...,1,1.0,0,109.662800,80.936730,6,4,16.0,17.0,5.400293
224,0,40,56.214679,155.177530,22.603586,11,80,20,10.3,2,...,0,0.0,0,125.833330,66.650530,11,9,17.0,18.0,4.910884
228,0,40,54.038228,155.298690,23.779234,11,80,20,10.3,2,...,0,0.0,0,124.752782,70.106417,11,9,17.0,18.0,4.905403
319,0,32,74.441128,162.430070,27.530920,11,72,18,10.8,2,...,1,0.0,1,117.008624,77.299527,3,3,14.0,13.0,9.136036
405,0,27,59.904946,158.873886,23.157590,15,70,18,10.8,2,...,1,0.0,0,111.056319,69.853622,8,5,18.0,15.0,9.660166
416,0,29,52.955206,159.581299,20.929324,15,72,18,10.2,2,...,1,1.0,0,107.397820,79.063894,6,4,16.0,17.0,6.496181
422,1,45,87.972480,151.979136,35.809881,15,72,18,12.0,4,...,1,1.0,0,117.956956,76.063568,10,15,15.0,17.0,8.509543
440,0,27,58.669283,161.469232,23.811056,15,70,18,10.8,2,...,1,0.0,0,112.581280,71.720413,8,5,18.0,15.0,9.641740
457,1,28,73.050063,164.385939,27.790414,15,72,18,12.0,2,...,1,1.0,0,113.374535,69.985740,4,6,10.0,12.0,9.399823
472,0,35,65.941098,155.737257,26.217148,15,80,22,10.7,2,...,1,1.0,1,104.802988,67.666240,4,4,15.0,14.0,8.994203
473,1,30,47.559757,155.015389,20.162987,15,72,20,10.8,2,...,0,0.0,1,117.283895,81.371440,9,19,19.0,18.0,6.383818
489,1,30,73.246933,150.168030,30.211225,16,74,18,11.7,4,...,0,1.0,0,122.650621,81.831581,8,6,12.0,11.0,4.785301
515,0,27,57.355638,160.946653,23.639723,15,70,18,10.8,2,...,1,0.0,0,109.600809,72.580898,8,5,18.0,15.0,8.667048
579,1,30,71.994483,151.107819,31.920279,16,74,18,11.7,4,...,0,1.0,0,117.324502,82.107929,8,6,12.0,11.0,4.286090
585,0,35,60.193803,156.120565,26.638955,15,80,22,10.7,2,...,1,1.0,1,108.087011,67.277567,4,4,15.0,14.0,10.014327
593,0,32,68.500503,163.148592,28.096178,11,72,18,10.8,2,...,1,0.0,1,118.247641,82.748627,3,3,14.0,13.0,9.230406
626,1,45,85.138053,154.285819,36.814510,15,72,18,12.0,4,...,1,1.0,0,118.005200,78.244352,10,15,15.0,17.0,8.032765
643,0,40,58.796957,155.911828,23.505633,11,80,20,10.3,2,...,0,0.0,0,122.631291,68.716950,11,9,17.0,18.0,4.968097
664,1,32,80.591256,163.635864,29.575248,18,72,18,11.5,4,...,1,1.0,0,114.466193,82.234880,9,12,15.0,15.0,10.198644
704,1,30,51.484508,153.497528,22.045968,15,72,20,10.8,2,...,0,0.0,1,125.461166,76.779303,9,19,19.0,18.0,5.510782
711,1,30,69.235135,148.546380,31.336020,16,74,18,11.7,4,...,0,1.0,0,116.686506,81.075836,8,6,12.0,11.0,4.597281
950,0,35,62.912512,154.681825,26.031861,15,80,22,10.7,2,...,1,1.0,1,106.750409,68.838131,4,4,15.0,14.0,9.997244
1022,1,45,85.748116,153.447792,38.090027,15,72,18,12.0,4,...,1,1.0,0,120.937795,83.662053,10,15,15.0,17.0,8.738630
1056,0,40,56.359421,155.249956,23.013575,11,80,20,10.3,2,...,0,0.0,0,116.038730,70.038002,11,9,17.0,18.0,4.295459
1073,0,29,53.855147,162.093832,20.736495,15,72,18,10.2,2,...,1,1.0,0,115.002884,77.758556,6,4,16.0,17.0,6.368825
1081,1,23,56.900877,152.088402,23.399266,13,78,18,10.8,2,...,1,0.0,1,111.064777,66.642693,10,18,14.0,14.0,10.029434
1273,1,28,76.910421,163.675686,28.241288,15,72,18,12.0,2,...,1,1.0,0,108.425465,70.544167,4,6,10.0,12.0,8.170797
1383,0,40,57.216646,155.548481,23.658048,11,80,20,10.3,2,...,0,0.0,0,116.957106,68.573956,11,9,17.0,18.0,4.231530
1407,1,45,81.960842,153.666184,35.745430,15,72,18,12.0,4,...,1,1.0,0,117.067272,76.939982,10,15,15.0,17.0,7.547882
1448,1,45,84.495823,153.687727,37.314770,15,72,18,12.0,4,...,1,1.0,0,124.664560,82.581712,10,15,15.0,17.0,8.723911
1472,0,40,58.082540,154.705142,23.114292,11,80,20,10.3,2,...,0,0.0,0,115.321908,68.310428,11,9,17.0,18.0,5.011101
1497,0,36,54.761218,152.827218,22.869010,13,74,18,10.0,2,...,0,1.0,0,109.531872,81.596323,4,1,22.0,14.0,10.209163
1569,1,45,88.651427,153.032222,36.629747,15,72,18,12.0,4,...,1,1.0,0,121.426667,78.874738,10,15,15.0,17.0,8.970073
1756,0,36,55.576922,153.635086,23.973474,13,74,18,10.0,2,...,0,1.0,0,114.519194,82.339693,4,1,22.0,14.0,10.277976
1786,0,32,73.604134,163.230859,28.178043,11,72,18,10.8,2,...,1,0.0,1,125.746951,76.072828,3,3,14.0,13.0,8.163939
1934,1,28,71.608145,165.960925,28.745188,15,72,18,12.0,2,...,1,1.0,0,114.142630,71.499310,4,6,10.0,12.0,8.291708
1971,1,30,48.728248,154.479797,20.813371,15,72,20,10.8,2,...,0,0.0,1,114.793214,76.635674,9,19,19.0,18.0,5.992793

In [43]:
data[data['Vit D3 (ng/mL)'] > 200]

,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),Hb(g/dl),Cycle(R/I),...,Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
219,1,29,64.290888,151.651260,28.125291,17,74,18,11.0,4,...,1,1.0,0,123.782087,68.017836,14,16,16.0,17.0,8.488744
220,1,35,58.195184,151.964259,25.720161,13,72,20,13.2,4,...,1,1.0,0,123.156787,77.494260,8,10,15.0,13.0,5.187475
832,1,35,57.819600,153.660756,24.448612,13,72,20,13.2,4,...,1,1.0,0,120.683491,77.595619,8,10,15.0,13.0,4.950329
1811,1,29,64.306168,153.629206,26.355756,17,74,18,11.0,4,...,1,1.0,0,125.071018,72.626258,14,16,16.0,17.0,9.149376

In [44]:
data[data['BP _Systolic (mmHg)'] < 50]

,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),Hb(g/dl),Cycle(R/I),...,Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
1463,0,38,71.114266,168.537859,24.748601,13,75,20,12.5,2,...,0,0.0,0,12.005677,79.965909,1,1,11.0,12.0,4.819840
1989,0,38,67.939927,171.514720,24.625635,13,75,20,12.5,2,...,0,0.0,0,11.525778,80.155633,1,1,11.0,12.0,4.764578

In [45]:
data[data['BP _Diastolic (mmHg)'] < 30]

,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),Hb(g/dl),Cycle(R/I),...,Pimples(Y/N),Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm)
641,0,30,45.129961,156.785188,19.070494,15,73,18,11.2,2,...,1,1.0,1,125.277511,7.680842,2,1,11.0,14.0,6.118522
1532,0,30,47.893503,157.648222,17.972145,15,73,18,11.2,2,...,1,1.0,1,119.568499,8.397874,2,1,11.0,14.0,5.969696
1717,0,30,45.450537,157.062255,19.368030,15,73,18,11.2,2,...,1,1.0,1,119.084657,7.994271,2,1,11.0,14.0,5.644595
1875,0,30,48.472556,159.134981,18.109400,15,73,18,11.2,2,...,1,1.0,1,125.323336,8.271484,2,1,11.0,14.0,6.097413

In [46]:
print("FSH >100:", len(data[data['FSH(mIU/mL)'] > 100]))
print("LH >100:", len(data[data['LH(mIU/mL)'] > 100]))
print("VitD >200:", len(data[data['Vit D3 (ng/mL)'] > 200]))
print("Systolic <50:", len(data[data['BP _Systolic (mmHg)'] < 50]))
print("Diastolic <30:", len(data[data['BP _Diastolic (mmHg)'] < 30]))

FSH >100: 0
LH >100: 7
VitD >200: 4
Systolic <50: 2
Diastolic <30: 4

In [47]:
median_lh = data['LH(mIU/mL)'].median()

data.loc[
    data['LH(mIU/mL)'] > 100,
    'LH(mIU/mL)'
] = median_lh

In [48]:
median_lh = data['LH(mIU/mL)'].median()

data.loc[
    data['LH(mIU/mL)'] > 100,
    'LH(mIU/mL)'
] = median_lh

In [49]:
median_fsh/lh = data['FSH/LH'].median()

data.loc[
    data['FSH/LH'] > 100,
    'FSH/LH'
] = median_fsh/lh

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (3704215364.py, line 1)

In [50]:
data1.corr()

ValueError: could not convert string to float: 'a'